---
- name: kind | Install kind with Go
  ansible.builtin.command:
    cmd: "go install {{ item.package }}"
    creates: "{{ ansible_facts['env']['HOME'] }}/go/bin/{{ item.cmd }}"
  loop_control:
    label: "{{ item.package }}"
  loop:
    - { package: sigs.k8s.io/kind@latest, cmd: kind }

