---
- name: "{{ role_name }} | Ubuntu | Check if glab is installed"
  ansible.builtin.command: which glab
  register: glab_check
  changed_when: false
  failed_when: false

- name: "{{ role_name }} | Ubuntu | Install from GitHub Release"
  ansible.builtin.include_role:
    name: github_release
  vars:
    repository: gitlab-org/cli
    binary_name: glab
    github_account: gitlab.com
  when: glab_check.rc != 0
