---
- name: "Hammerspoon | MacOSX | {{ current_spoon }} | Detect local instance of {{ current_spoon }}"
  ansible.builtin.stat:
    path: "{{ ansible_facts['user_dir'] }}/.hammerspoon/Spoons/{{ current_spoon }}.spoon"
  register: hammerspoon_current_spoon

- name: "Hammerspoon | MacOSX | {{ current_spoon }} | Download latest {{ current_spoon }}"
  when: not hammerspoon_current_spoon.stat.exists
  block:
    - name: "Hammerspoon | MacOSX | {{ current_spoon }} | Download latest {{ current_spoon }}"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/Hammerspoon/Spoons/master/Spoons/{{ current_spoon }}.spoon.zip"
        dest: "{{ ansible_facts['user_dir'] }}/.hammerspoon/Spoons/{{ current_spoon }}.spoon.zip"
        mode: "0644"

    - name: "Hammerspoon | MacOSX | {{ current_spoon }} | Install {{ current_spoon }}"
      ansible.builtin.unarchive:
        src: "{{ ansible_facts['user_dir'] }}/.hammerspoon/Spoons/{{ current_spoon }}.spoon.zip"
        dest: "{{ ansible_facts['user_dir'] }}/.hammerspoon/Spoons"
        remote_src: true

    - name: "Hammerspoon | MacOSX | {{ current_spoon }} | Cleanup latest {{ current_spoon }} zip"
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.hammerspoon/Spoons/{{ current_spoon }}.spoon.zip"
        state: absent
