---
# K9s installation using github-release role

- name: "K9s | Install from GitHub releases"
  ansible.builtin.include_role:
    name: github_release
  vars:
    github_release_repo: "derailed/k9s"
    github_release_binary_name: "k9s"
    github_release_check_command: "/usr/local/bin/k9s version -s"
    github_release_version_pattern: "v[0-9]+\\.[0-9]+\\.[0-9]+"
    github_release_owner: "{{ host_user }}"
    github_release_group: "{{ host_user }}"

- name: "K9s | Ensure k9s config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/k9s"
    state: directory
    mode: "0755"

- name: "K9s | Ensure k9s skins directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/k9s/skins"
    state: directory
    mode: "0755"

- name: "K9s | Copy skin config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/k9s/skins/catppuccin_mocha.yaml"
    src: "catppuccin_mocha.yaml"
    mode: "0644"

- name: "K9s | Copy config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/k9s/config.yaml"
    src: "config.yaml"
    mode: "0644"