---
- name: Lua | Update DNF cache
  dnf:
    update_cache: true
  become: true

- name: Lua | Install Lua
  dnf:
    name: "{{ item }}"
  become: true
  loop:
    - lua
    - luarocks
    - luajit

- name: Lua | Gather installed lua rocks
  command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false

# - name: Lua | Install Lua modules
#   command:
#     cmd: luarocks install {{ item }} --lacal
#   loop:
#     - luabitop
#   when: item not in rocks.stdout
