---
- name: Install GitHub CLI tool
  ansible.builtin.dnf:
    name: gh
    state: present
  become: true

# - name: Authenticate with GitHub using SSH key
#   command: gh auth login --hostname github.com --method ssh
