---
- name: "GH | MacOSX | Install gh"
  community.general.homebrew:
    name: gh
    state: present

- name: "GH | MacOSX | Install gh-dash"
  ansible.builtin.command:
    cmd: gh extension install dlvhdr/gh-dash
