---
- name: DotFiles Config
  hosts: localhost
  connection: local

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Check for user overrides
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/overrides/group_vars/user.yml"
      register: user_overrides_file
      tags:
        - always

    - name: Load user overrides
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/overrides/group_vars/user.yml"
      when: user_overrides_file.stat.exists
      tags:
        - always

    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User (WSL)
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

    - name: Detect Sudo
      ansible.builtin.import_tasks: pre_tasks/detect_sudo.yml
      tags:
        - always

    - name: Detect 1Password
      ansible.builtin.import_tasks: pre_tasks/detect_1password.yml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        # yamllint disable-line rule:line-length
        run_roles: "{% if ansible_run_tags | list == ['all'] %}{{ default_roles | reject('in', exclude_roles | default([])) | list }}{% else %}{{ (default_roles | select('in', ansible_run_tags) | list) + (ansible_run_tags | reject('in', default_roles) | reject('equalto', 'all') | list) }}{% endif %}"
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
