---
# Test playbook for github-release role
- name: Test GitHub Release Role
  hosts: localhost
  connection: local
  vars:
    host_user: "{{ ansible_user_id }}"
  
  tasks:
    - name: Create test directory
      ansible.builtin.file:
        path: /tmp/test-bin
        state: directory
        mode: "0755"

    - name: Test 1 - Install lazygit (tar.gz)
      ansible.builtin.include_role:
        name: github_release
      vars:
        github_release_repo: "jesseduffield/lazygit"
        github_release_binary_name: "lazygit"
        github_release_install_path: "/tmp/test-bin"
        github_release_check_command: "/tmp/test-bin/lazygit --version"
        github_release_force_install: true  # Force install to test location
        github_release_become: false
        github_release_owner: "{{ ansible_user_id }}"
        github_release_group: "{{ ansible_real_group_id }}"

    - name: Verify lazygit installation
      ansible.builtin.command:
        cmd: /tmp/test-bin/lazygit --version
      register: lazygit_version
      changed_when: false

    - name: Display lazygit version
      ansible.builtin.debug:
        msg: "Lazygit installed: {{ lazygit_version.stdout }}"

    - name: Test 2 - Install specific version of gh CLI
      ansible.builtin.include_role:
        name: github_release
      vars:
        github_release_repo: "cli/cli"
        github_release_binary_name: "gh"
        github_release_tag: "v2.40.0"
        github_release_install_path: "/tmp/test-bin"
        github_release_become: false
        github_release_owner: "{{ ansible_user_id }}"
        github_release_group: "{{ ansible_real_group_id }}"

    - name: Verify gh installation
      ansible.builtin.command:
        cmd: /tmp/test-bin/gh --version
      register: gh_version
      changed_when: false

    - name: Display gh version
      ansible.builtin.debug:
        msg: "GitHub CLI installed: {{ gh_version.stdout }}"

    # Skip cleanup to allow manual testing
    # - name: Cleanup test directory
    #   ansible.builtin.file:
    #     path: /tmp/test-bin
    #     state: absent