---
- name: "Asciiquarium | Detect any installed versions"
  ansible.builtin.command:
    cmd: which asciiquarium
  changed_when: false
  failed_when: false
  register: is_installed

- name: "Asciiquarium | Register any installed versions"
  ansible.builtin.set_fact:
    is_installed: "{{ is_installed.stdout|default('') }}"

- name: "Asciiquarium | Installed versions"
  ansible.builtin.debug:
    var: is_installed

- name: Install
  block:
    - name: "Asciiquarium | Install Dependencies"
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - make
        - cpanminus
      become: true

    - name: "Asciiquarium | Ensure clean location to download tarball"
      ansible.builtin.file:
        path: /tmp/asciiquarium.tar.gz
        state: absent

    - name: "Asciiquarium | Download the asciiquarium tarball"
      ansible.builtin.get_url:
        url: https://robobunny.com/projects/asciiquarium/asciiquarium.tar.gz
        dest: /tmp/asciiquarium.tar.gz
      notify:
        - Remove tarball

    - name: "Asciiquarium | Extract the tarball"
      ansible.builtin.unarchive:
        src: /tmp/asciiquarium.tar.gz
        dest: /tmp/
      when: not ansible_check_mode

    - name: "Asciiquarium | Install libcurses-perl"
      ansible.builtin.dnf:
        name: perl-curses
        state: present
      become: true

    - name: "Asciiquarium | Install Term::Animation from CPAN"
      ansible.builtin.cpanm:
        name: Term::Animation
      become: true

    - name: "Asciiquarium | Install"
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/asciiquarium_1.1/asciiquarium
        dest: /usr/local/bin/
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        force: true
        mode: 0755
      become: true
      notify:
        - Remove extracted tarball
      when: is_installed | length < 1
