#!/usr/bin/env bash
alias xsc="xclip -selection clipboard"
alias python="python3"
alias yolo="git push origin master --force --no-verify"
alias dotFileInstall="$DOTFILES/install"
alias pjson="python -mjson.tool"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"

alias update='sudo nala update && sudo nala upgrade -y && sudo nala autoremove -y'
alias t=terraform
alias g='git'
alias gs='git status'
alias gcane='git commit --amend --no-edit'
alias ggl='git log --oneline --graph'
alias ll='ls -halF'
alias bt='bpytop'
alias vi='nvim'
alias vim='nvim'
alias ni='nvim'
alias c='clear'
alias d='docker'
alias dprune='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias dsysprune='docker system prune -af'
alias k='kubectl'
alias kx='kubectl exec -it'
alias ugr='pwsh -c Update-GitRepos'
alias brb=asciiquarium
alias aq=asciiquarium
alias gotest='go clean -testcache;go test ./...'
alias cgone='gone -s '

if [ -x "$(command -v zoxide)" ]; then
  eval "$(zoxide init bash)"
fi

source /usr/share/bash-completion/completions/git
# Main git completions (prior to git 2.30, you an use _git instead of __git_main)
alias g="git"
__git_complete g __git_main

alias gc="git checkout"
alias gcb="git checkout -b"
__git_complete gc _git_checkout
__git_complete gcb _git_checkout

alias gp="git push"
alias gpf="git push --force-with-lease"
__git_complete gp _git_push




