---
- name: "NPM | Install"
  ansible.builtin.apt:
    name:
      - npm
    state: latest
  become: true

- name: "NPM | Install N"
  ansible.builtin.command: npm install -g n
  become: true

- name: "NPM | Install NodeJS"
  ansible.builtin.command: n stable
  become: true


