---
- name: "NPM | Install"
  ansible.builtin.apt:
    name:
      - npm
    state: latest
  become: true

- name: "NPM | Install NodeJS"
  community.general.npm:
    name: "node"
    global: true
    state: latest
  become: true



