---
- name: "{{ role_name }} | Ubuntu | Check if npm is installed"
  ansible.builtin.command: which npm
  register: npm_check
  changed_when: false
  failed_when: false

- name: "{{ role_name }} | Ubuntu | Install opencode via npm"
  ansible.builtin.command: npm install -g opencode-ai
  when: npm_check.rc == 0
  changed_when: true

- name: "{{ role_name }} | Ubuntu | Install via curl if npm not available"
  ansible.builtin.shell: curl -fsSL https://opencode.ai/install | bash
  when: npm_check.rc != 0
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/opencode"
  changed_when: true
