---
- name: Cleanup go downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ go_file }}.tar.gz"
    state: absent
  become: true
  when: not ansible_check_mode

- name: Remove extracted go directory
  ansible.builtin.file:
    path: /tmp/go
    state: absent
  become: true
  when: not ansible_check_mode
