---
- name: K8s | Adding kubernetes dnf module
  ansible.builtin.dnf:
    name: "dnf-plugins-core"
    state: present
  become: true

- name: K8s | Adding kubernetes repo
  ansible.builtin.dnf:
    name: "kubernetes"
    description: "Kubernetes Repository"
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    enabled: yes
  become: true

- name: K8s | Installing Kubernetes
  ansible.builtin.dnf:
    name: "{{ item.name }}-{{ item.version | default('*') }}"
    state: present
    enablerepo: "kubernetes"
  become: true
  loop: "{{ k8s.package_versions[ansible_hostname] | default(k8s.package_versions.default) }}"

- name: K8s | Preventing unintended upgrades
  ansible.builtin.dpkg_selections:
    name: "{{ item.name }}"
    selection: hold
  become: true
  loop: "{{ k8s.package_versions[ansible_hostname] | default(k8s.package_versions.default) }}"

- name: K8s | Configure .kube/config
  block:
    - name: K8s | Ensure .kube directory exists
      ansible.builtin.file:
        path: "~/.kube"
        state: directory
        mode: "0755"

    - name: K8s | Copy .kube/config file
      ansible.builtin.copy:
        src: config
        dest: "~/.kube/config"
        mode: "0600"
