[regions.full]
x = "2%"
y = "4%"
w = "96%"
h = "92%"
float = true

[regions.main]
x = "2%"
y = "4%"
w = "60%"
h = "92%"
float = true

[regions.wide]
x = "2%"
y = "4%"
w = "74%"
h = "92%"
float = true

[regions.side]
x = "64%"
y = "4%"
w = "34%"
h = "92%"
float = true

[regions.chat]
x = "62%"
y = "7%"
w = "36%"
h = "86%"
float = true

[regions.center_left]
x = "8%"
y = "15%"
w = "55%"
h = "69%"
float = true

[regions.center]
x = "23%"
y = "15%"
w = "54%"
h = "66%"
float = true

[regions.left]
x = "2%"
y = "4%"
w = "47%"
h = "92%"
float = true

[regions.right]
x = "51%"
y = "4%"
w = "47%"
h = "92%"
float = true

[regions.top_right]
x = "51%"
y = "4%"
w = "47%"
h = "44%"
float = true

[regions.right_small]
x = "60%"
y = "22%"
w = "38%"
h = "55%"
float = true

[regions.bottom_right]
x = "51%"
y = "52%"
w = "47%"
h = "44%"
float = true
