[regions.full]
x = "0%"
y = "0%"
w = "100%"
h = "100%"
float = true

[regions.main]
x = "0%"
y = "0%"
w = "65%"
h = "100%"
float = true

[regions.wide]
x = "0%"
y = "0%"
w = "80%"
h = "100%"
float = true

[regions.side]
x = "65%"
y = "0%"
w = "35%"
h = "100%"
float = true

[regions.chat]
x = "62.5%"
y = "5%"
w = "35%"
h = "50%"
float = true

[regions.center_left]
x = "7.5%"
y = "12.5%"
w = "55%"
h = "75%"
float = true

[regions.center]
x = "12.5%"
y = "12.5%"
w = "75%"
h = "75%"
float = true

[regions.left]
x = "0%"
y = "0%"
w = "50%"
h = "100%"
float = true

[regions.right]
x = "50%"
y = "0%"
w = "50%"
h = "100%"
float = true

[regions.top_right]
x = "62.5%"
y = "5%"
w = "35%"
h = "50%"
float = true

[regions.right_small]
x = "60%"
y = "20%"
w = "37.5%"
h = "60%"
float = true

[regions.bottom_right]
x = "62.5%"
y = "50%"
w = "35%"
h = "45%"
float = true

[regions.hd_left_main]
x = "0%"
y = "0%"
w = "60%"
h = "100%"
float = true

[regions.hd_right_side]
x = "60%"
y = "0%"
w = "40%"
h = "100%"
float = true

[regions.hd_float_center]
x = "12.5%"
y = "10%"
w = "75%"
h = "80%"
float = true

[regions.standard_browser_left]
x = "0%"
y = "0%"
w = "40%"
h = "100%"
float = true

[regions.standard_terminal_right]
x = "40%"
y = "0%"
w = "60%"
h = "100%"
float = true

[regions.standard_utility_overlay]
x = "12.5%"
y = "10%"
w = "75%"
h = "80%"
float = true
