---
- name: "Kubewarden | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubewarden/kwctl/releases/latest
  register: kwctl_latest_version_json
  changed_when: false

- name: "Kubewarden | Registering kwctl Latest Release"
  ansible.builtin.set_fact:
    kwctl_latest_release: "{{ kwctl_latest_version_json.json.tag_name }}"

- name: "Kubewarden | Registering kwctl Latest Version"
  ansible.builtin.set_fact:
    kwctl_latest_version: "{{ kwctl_latest_release.stdout | default('') }}"

- name: "Kubewarden | Getting version information"
  ansible.builtin.shell:
    cmd: /usr/local/bin/kwctl --version | grep -oP 'version=\K[^,]+' | awk 'NR==1' | sed 's/^/v/'
  args:
    executable: /bin/bash
  register: current_kwctl_version
  changed_when: false
  failed_when: false
#
- name: "Kubewarden | Show current_kwctl_version debug"
  ansible.builtin.debug:
    var: current_kwctl_version.stdout

- name: "Kubewarden | Show kwctl_latest_release debug"
  ansible.builtin.debug:
    var: kwctl_latest_release

- name: "Kubewarden | Install"
  when: kwctl_latest_release not in current_kwctl_version.stdout|default('')
  block:
    # regex_replace('^.', '') removes the first character from the string (the 'v' in the version number)
    - name: "Kubewarden | Define kwctl_file"
      ansible.builtin.set_fact:
        kwctl_file: "kwctl-linux-x86_64"

    - name: "Kubewarden | Ensure clean download destination"
      ansible.builtin.file:
        path: "/tmp/{{ kwctl_file }}.tar.gz"
        state: absent
      become: true

    - name: "Kubewarden | Downloading kwctl Release"
      ansible.builtin.get_url:
        url: "https://github.com/kubewarden/kwctl/releases/download/{{ kwctl_latest_release }}/{{ kwctl_file }}.zip"
        dest: /tmp/
        mode: "0644"
        force: true
      notify:
        - Cleanup kwctl downloaded tar

    - name: "Kubewarden | Ensure clean extraction destination"
      ansible.builtin.file:
        path: "/tmp/kwctl"
        state: absent
      become: true

    - name: "Kubewarden | Extract kwctl tar file"
      ansible.builtin.unarchive:
        src: "/tmp/{{ kwctl_file }}.zip"
        dest: /tmp

    - name: "Kubewarden | Remove any current kwctl installations"
      ansible.builtin.file:
        path: /usr/local/bin/kwctl
        state: absent
      become: true

    - name: "Kubewarden | Install kwctl"
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/kwctl-linux-x86_64
        dest: /usr/local/bin/kwctl
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        force: true
        mode: "0755"
      become: true
      notify:
        - Remove extracted kwctl directory
