#!/usr/bin/env bash
# Cell Generate Rules - Auto-generate window rules from cell assignments
# Creates window-rules.conf that can be sourced in hyprland.conf

# Get script directory and source manager functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/cell-manager.sh"

OUTPUT="$CELL_DIR/window-rules.conf"

# Create output file
cat > "$OUTPUT" <<'HEADER'
# Auto-generated window rules for cell system
# DO NOT EDIT MANUALLY - This file is generated by cell-generate-rules.sh
# Generated:
HEADER

# Add generation timestamp
sed -i "s/Generated: .*/Generated: $(date)/" "$OUTPUT"

echo "" >> "$OUTPUT"
echo "# ========================================" >> "$OUTPUT"
echo "# CELL-BASED WINDOW RULES" >> "$OUTPUT"
echo "# ========================================" >> "$OUTPUT"

# Process each assignment
while IFS=: read -r class key cell; do
    # Skip empty lines and comments
    [[ -z "$class" || "$class" =~ ^# ]] && continue

    # Get cell dimensions
    dims=$(get_cell_dimensions "$cell")

    if [ -z "$dims" ]; then
        echo "# Warning: Cell $cell not found for $class" >> "$OUTPUT"
        continue
    fi

    move=$(echo "$dims" | cut -d' ' -f1-2)
    size=$(echo "$dims" | cut -d' ' -f3-4)

    echo "" >> "$OUTPUT"
    echo "# $class -> Cell $cell (F13+$key)" >> "$OUTPUT"
    echo "windowrulev2 = float, class:^($class)$" >> "$OUTPUT"
    echo "windowrulev2 = size $size, class:^($class)$" >> "$OUTPUT"
    echo "windowrulev2 = move $move, class:^($class)$" >> "$OUTPUT"
done < "$CELL_DIR/assignments.conf"

echo "" >> "$OUTPUT"
echo "# ========================================" >> "$OUTPUT"
echo "# END OF AUTO-GENERATED RULES" >> "$OUTPUT"
echo "# ========================================" >> "$OUTPUT"

echo "Window rules generated successfully: $OUTPUT"
