---
- name: "Python | Install"
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true

- name: "Python | Install pip packages"
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - bpytop
    - shell-gpt==0.9.0

- name: "Python | Ensure bpytop directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/bpytop

- name: "Python | Copy bpytop config"
  ansible.builtin.copy:
    src: bpytop.conf
    dest: ~/.config/bpytop/bpytop.conf
    mode: "0644"
