---
# macOS-specific installation tasks
# Demonstrates Homebrew installation pattern

- name: "{{ role_name }} | MacOSX | Install via Homebrew"
  community.general.homebrew:
    name: "{{ role_name }}"
    state: present
  register: example_brew_install

# Example of installing additional dependencies
- name: "{{ role_name }} | MacOSX | Install dependencies"
  community.general.homebrew:
    name:
      - dependency1
      - dependency2
    state: present
  when: install_dependencies | default(true)

# Example of macOS-specific configuration
- name: "{{ role_name }} | MacOSX | Set macOS-specific config"
  ansible.builtin.copy:
    src: "macos-specific-config.plist"
    dest: "{{ ansible_user_dir }}/Library/Preferences/com.example.{{ role_name }}.plist"
    mode: "0644"
  when: example_brew_install is succeeded

# Note: Homebrew on macOS doesn't require sudo
# Package installation is possible without privilege escalation