---
- name: "{{ role_name }} | MacOSX | Install | Codex CLI"
  community.general.homebrew_cask:
    name: codex
    state: present

- name: "{{ role_name }} | MacOSX | Remove legacy peon-ping"
  community.general.homebrew:
    name: peonping/tap/peon-ping
    state: absent

- name: "{{ role_name }} | MacOSX | Remove legacy peon-ping Homebrew tap"
  community.general.homebrew_tap:
    name: peonping/tap
    state: absent
