---
- name: "{{ role_name }} | MacOSX | Install | Codex CLI"
  community.general.homebrew_cask:
    name: codex
    state: present

- name: "{{ role_name }} | MacOSX | Install | peon-ping"
  community.general.homebrew:
    name: peon-ping
    state: present
