---
- name: "Zsh | Install Zsh"
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: "Zsh | Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true
