---
role_name: plasma

plasma_enable_sddm: true
plasma_enable_kwin_summon: true
plasma_start_summon_service: true
plasma_summon_script_id: plasma-summon

plasma_local_bin_dir: "{{ ansible_facts['user_dir'] }}/.local/bin"
plasma_config_dir: "{{ ansible_facts['user_dir'] }}/.config/plasma-summon"
plasma_systemd_user_dir: "{{ ansible_facts['user_dir'] }}/.config/systemd/user"
plasma_kwin_scripts_dir: "{{ ansible_facts['user_dir'] }}/.local/share/kwin/scripts"

plasma_arch_packages:
  - plasma-meta
  - sddm
  - xdg-desktop-portal-kde
  - qt6-wayland
  - qt6-tools
  - xorg-xwayland
  - dolphin
  - konsole
  - systemsettings
  - spectacle
  - ark
  - kate
  - kcalc
  - kdialog
  - kpackage
  - kconfig
  - python
  - python-dbus-next
