local positions = require('positions')

return {
  {
    key = 'fourk',
    name = '4K Workspace',
    profiles = { 'fourk' },
    cells = {
      { positions.fourk.left_large,        positions.full },
      { positions.fourk.right_side,        positions.full },
      { positions.fourk.top_right,         positions.full },
      { positions.fourk.center_left_large, positions.full },
      { positions.fourk.center_large,      positions.full },
      { positions.fourk.right_small,       positions.full },
    },
    apps = {
      Terminal    = { cell = 1, open = true },
      Browser     = { cell = 2, open = true },
      Signal      = { cell = 3 },
      Discord     = { cell = 3 },
      Outlook     = { cell = 4 },
      Spotify     = { cell = 4 },
      Finder      = { cell = 4 },
      OnePassword = { cell = 4 },
      Teams       = { cell = 5 },
      Obsidian    = { cell = 3 },
      ChatGPT     = { cell = 6 },
      Codex       = { cell = 6 },
      Agenda      = { cell = 6 },
    },
  },
  {
    key = 'fullscreen',
    name = 'Fullscreen',
    profiles = { 'builtin', 'fullscreen' },
    cells = {
      { positions.full, positions.full },
    },
    apps = {
      Terminal    = { cell = 1, open = true },
      Browser     = { cell = 1, open = true },
      Signal      = { cell = 1 },
      Discord     = { cell = 1 },
      Outlook     = { cell = 1 },
      Spotify     = { cell = 1 },
      Finder      = { cell = 1 },
      OnePassword = { cell = 1 },
      Teams       = { cell = 1 },
      Obsidian    = { cell = 1 },
      ChatGPT     = { cell = 1 },
      Codex       = { cell = 1 },
      Agenda      = { cell = 1 },
    },
  },
  {
    key = 'hd',
    name = 'HD Workspace',
    profiles = { 'standard' },
    cells = {
      { positions.hd.left_main,    positions.full },
      { positions.hd.right_side,   positions.full },
      { positions.hd.float_center, positions.full },
    },
    apps = {
      Terminal    = { cell = 1, open = true },
      Browser     = { cell = 2, open = true },
      Signal      = { cell = 3 },
      Discord     = { cell = 3 },
      Outlook     = { cell = 3 },
      Spotify     = { cell = 3 },
      Finder      = { cell = 3 },
      OnePassword = { cell = 3 },
      Teams       = { cell = 3 },
      Obsidian    = { cell = 3 },
      ChatGPT     = { cell = 3 },
      Codex       = { cell = 3 },
      Agenda      = { cell = 3 },
    },
  },
  {
    key = 'standard',
    name = 'Standard Dev',
    profiles = { 'ultrawide' },
    cells = {
      { positions.standard.standard_browser_left,    positions.full },
      { positions.standard.standard_terminal_right,  positions.full },
      { positions.standard.standard_utility_overlay, positions.full },
    },
    apps = {
      Browser     = { cell = 1, open = true },
      Terminal    = { cell = 2, open = true },
      Windows     = { cell = 2 },
      Signal      = { cell = 3 },
      Spotify     = { cell = 3 },
      Outlook     = { cell = 3 },
      Finder      = { cell = 3 },
      Teams       = { cell = 3 },
      Obsidian    = { cell = 3 },
      ChatGPT     = { cell = 3 },
      Codex       = { cell = 3 },
      OnePassword = { cell = 3, open = true },
      Agenda      = { cell = 3 },
      Discord     = { cell = 3, open = true },
    },
  },
}
