- name: Check if Discord is installed
  command: dpkg-query -W -f='${Version}' discord
  register: discord_installed
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Register installed Discord version as Ansible fact
  set_fact:
    discord_version: "{{ discord_installed.stdout }}"
  when: discord_installed.rc == 0

- name: Get Discord Ubuntu installer
  get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
  when: discord_installed.rc != 0 or discord_version < "NEW_VERSION"

- name: Install Discord
  apt:
    deb: /tmp/discord.deb
    state: present
  when: discord_installed.rc != 0 or discord_version < "NEW_VERSION"

