---
galaxy_info:
  author: TechDufus
  description: Generic GitHub Release downloader and installer
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - github
    - releases
    - download
    - installer
    - automation

dependencies: []

