---
- name: Initialize 1Password facts
  ansible.builtin.set_fact:
    op_installed: false
    op_authenticated: false

- name: Detect 1Password CLI
  ansible.builtin.command:
    cmd: which op
  changed_when: false
  failed_when: false
  register: op_binary_check

- name: Register 1Password installation state
  ansible.builtin.set_fact:
    op_installed: "{{ op_binary_check.rc == 0 }}"

- name: Detect 1Password authentication state
  ansible.builtin.command:
    cmd: op whoami
  changed_when: false
  failed_when: false
  register: op_whoami
  when: op_installed

- name: Register 1Password authentication state
  ansible.builtin.set_fact:
    op_authenticated: "{{ op_whoami.rc == 0 }}"
  when: op_installed
