---
- name: Detect WSL
  ansible.builtin.shell: |
    if [[ $(cat /proc/version | grep microsoft.*WSL) ]]; then
      echo true
    else
      echo false
    fi
  register: ansible_host_environment_is_wsl
  args:
    executable: /bin/bash
  ignore_errors: true
  changed_when: false

- name: Register WSL State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_wsl: "{{ ansible_host_environment_is_wsl.stdout | bool }}"

- name: Show WSL State
  ansible.builtin.debug:
    msg: "WSL State: '{{ ansible_host_environment_is_wsl }}'"
