---
- name: Cleanup kwctl downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ kwctl_file }}.zip"
    state: absent
  become: true

- name: Remove extracted kwctl directory
  ansible.builtin.file:
    path: /tmp/{{ kwctl_file }}*
    state: absent
  become: true
