---
modelRoles:
  default: openai-codex/gpt-6.1-sol:max
  smol: openai-codex/gpt-6.1-sol:low
  tiny: openai-codex/gpt-6.1-sol:low
  task: openai-codex/gpt-6.1-sol
  slow: openai-codex/gpt-6-astra
  plan: openai-codex/gpt-6-astra
  designer: openai-codex/gpt-6-astra
  vision: openai-codex/gpt-6.1-sol:high
  commit: openai-codex/gpt-6.1-sol:low
  reviewer: openai-codex/gpt-6.1-sol
  advisor: openai-codex/gpt-6.1-sol:medium
enabledModels:
  - openai-codex/*
