[[sessions]]
name = "dotfiles"
path = "~/.dotfiles"

# Default session configuration
[default_session]
startup_command = "tmux split-window -h -p 50 && tmux select-pane -L && claude --continue"
startup_window_name = "main"
