---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure config dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Ensure 1Password config dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/1Password"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Ensure ssh 1Password config dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/1Password/ssh"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Deploy ssh config"
  ansible.builtin.copy:
    src: agent.toml
    dest: "{{ ansible_user_dir }}/.config/1Password/ssh/agent.toml"
    mode: "0644"
