---
- name: "Fonts | MacOSX | Install BerkeleyMono Nerd Font"
  ansible.builtin.include_tasks: private_berkeley_mono.yml
  vars:
    berkeley_mono_install_dir: "{{ ansible_env.HOME }}/Library/Fonts"
    berkeley_mono_refresh_cache: false
